### PR TITLE
Preact Support

### PR DESCRIPTION
**Pull request by sanpoChew**
We've just gone through the process of dropping preact-compat in favour of a fully preact codebase and thought this might be useful for other people too. This was done quickly and dirtily, if you're interested in getting it merged I would have a tidy-up but I just wanted to open this for discussion really. I've also done a fork of react-component-queries, but that relies on this so I thought I'd open it here.

### CODE REVIEW

**Comment by ctrlplusb** [comment]
Hey @sanpoChew - awesome thanks for picking this up. I am completely supportive of any implementation that will support both React and Preact. 👍

More than happy for you to run with this. Let me know when you would like me to review. 👍

**Comment by sanpoChew** [comment]
@ctrlplusb great news! It all seems to work as of now, we're using it in production. I have some ideas about tweaking the build process and need to fix the test coverage but then it should be ready for you to have a look.

**Comment by ctrlplusb** [comment]
Awesome.  I was wanting to change the build process over to use rollup and remove the dist/build folders from source control.  Just haven't had time for it yet.  My newer libs are using this configuration (e.g. [`react-app-rewire-modernizr`](https://github.com/ctrlplusb/react-app-rewire-modernizr)).

**Comment by sanpoChew** [comment]
@ctrlplusb I've let this get way too far behind master, going to checkout into a new branch and just reimplement it, then I'll open a new pull request

**Comment by ctrlplusb** [comment]
Amazing @sanpoChew - look forward to it 👍

**Comment by sanpoChew** [comment]
@ctrlplusb I've been thinking about the best way to do this, is it preferable to you that I reimplement in the same way this merge request was done where there's two sets of source code or would it be better for me to do a branch that replaces all the react-specific code and you could keep this on a separate branch and release it as a separate package? 

Right now the only issue is inevitable peer dependency warnings but I'm a bit worried about the massive amount of code duplication, seems like it would inevitably cause problems. I originally did it that way because i took inspiration from https://github.com/developit/unistore but their codebase is so small that it doesn't particularly matter.

**Comment by ctrlplusb** [comment]
The other alternative is for you to fork the project, maintaining a `preact-sizeme` that is free of any react specific dependencies. I would be more than happy to link to your repo too. 👍

Thinking about it I think this will probably be the easiest and cleanest option.

What do you think?

**Comment by sanpoChew** [comment]
Hey @ctrlplusb those have been published now at:

https://www.npmjs.com/package/preact-sizeme

https://www.npmjs.com/package/preact-component-queries

👍

**Pull request closed without merging**
