### PR TITLE
Support react 17 peer dependency.

### PR DESCRIPTION
**Pull request by bcomnes**
Simple change, just increases the semver range of the react peer deps.  Everything working good on 17 from what I can tell.

### CODE REVIEW

**Comment by Hypnosphi** [comment]
@ctrlplusb can you please review

**Comment by bcomnes** [comment]
Any chance for a quick review/merge/release?  Would really help downstream issues with the new npm 7 peer dep changes. Thank you!

**Comment by bcomnes** [comment]
Happy new year! Is there anything I can do to help land this?

**Comment by Hypnosphi** [comment]
I've published your fork as `@hypnosphi/react-sizeme`

**Comment by bcomnes** [comment]
Awesome thank you @Hypnosphi for making this happen.

**Comment by brodybits** [comment]
Bump with a caveat: updating to react@17 gives me some test failures, needs further investigation.

**Comment by ctrlplusb** [comment]
I shall publish a version of this soon. 🙏

**Comment by brodybits** [comment]
Thanks for taking care of the updates !!

**Pull request closed without merging**
